export const books = [
 {
  id:1,
  title: "India 2020",
    author: "A.P.J. Abdul Kalam",
    category: "Vision / Politics",
    rating: 4.5,
    reviews: 9800,
    price: 229,
    cover: "https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg",
    description: "A vision for transforming India into a developed nation.",
    pages: 326,
    publisher: "Penguin India",
    year: 1998,
    badge: "Inspirational",
    featured: true,
 },
  {
    id: 2,
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    price: 999,
    rating: 4.8,
    reviews: 3241,
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80",
    description:
      "Between life and death there is a library. When Nora Oliphany finds herself in the Midnight Library, she has a chance to make things right.",
    pages: 304,
    publisher: "Canongate Books",
    year: 2020,
    badge: "Bestseller",
    featured: true,
  },
  {
    id: 3,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
    price: 499.00,
    rating: 4.9,
    reviews: 5872,
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
    description:
      "Tiny changes, remarkable results. An easy and proven way to build good habits and break bad ones.",
    pages: 320,
    publisher: "Avery",
    year: 2018,
    badge: "Top Rated",
    featured: true,
  },
  {
    id: 4,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    price: 449,
    rating: 4.7,
    reviews: 4120,
    cover: "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&q=80",
    description:
      "A brief history of humankind—exploring the ways in which biology and history have defined us.",
    pages: 443,
    publisher: "Harper",
    year: 2015,
    badge: null,
    featured: true,
  },
  {
    id: 5,
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    price: 1029,
    rating: 4.9,
    reviews: 6003,
    cover: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&q=80",
    description:
      "Set on the desert planet Arrakis, Dune is the story of Paul Atreides—and the rise of a legend.",
    pages: 688,
    publisher: "Ace Books",
    year: 1965,
    badge: "Classic",
    featured: true,
  },
  {
    id: 6,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Finance",
    price: 829,
    rating: 4.8,
    reviews: 2987,
    cover: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&q=80",
    description:
      "Timeless lessons on wealth, greed, and happiness. Doing well with money isn't necessarily about what you know.",
    pages: 256,
    publisher: "Harriman House",
    year: 2020,
    badge: "New",
    featured: true,
  },
  {
    id: 7,
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Sci-Fi",
    price: 799,
    rating: 4.9,
    reviews: 4455,
    cover: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=400&q=80",
    description:
      "A lone astronaut must save the earth from disaster—but he can't remember who he is, where he is, or how he got there.",
    pages: 476,
    publisher: "Ballantine Books",
    year: 2021,
    badge: "New",
    featured: true,
  },
  {
    id: 8,
    title: "Deep Work",
    author: "Cal Newport",
    category: "Self-Help",
    price: 949,
    rating: 4.7,
    reviews: 3100,
    cover: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&q=80",
    description:
      "Rules for focused success in a distracted world. Professional activities performed in a state of distraction-free concentration.",
    pages: 296,
    publisher: "Grand Central",
    year: 2016,
    badge: null,
    featured: true,
  },
  {
    id: 9,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    price: 999,
    rating: 4.5,
    reviews: 7821,
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
    description:
      "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    pages: 180,
    publisher: "Scribner",
    year: 1925,
    badge: "Classic",
    featured: true,
  },
  {
    id: 10,
     title: "Chanakya Neeti",
    author: "Chanakya",
    category: "Philosophy",
    rating: 4.3,
    reviews: 889,
    price: 149,
    cover: "https://images-na.ssl-images-amazon.com/images/I/71HMyqG6MRL.jpg",
    description: "Ancient Indian wisdom on politics, strategy, and life lessons that remain relevant today.",
    pages: 220,
    publisher: "Fingerprint Publishing",
    year: 2017,
    badge: "Trending",
    featured: true,
  },
  {
    id: 11,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    price: 159,
    rating: 4.7,
    reviews: 9102,
    cover: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&q=80",
    description:
      "A fable about following your dream. A young Andalusian shepherd's journey to find his treasure.",
    pages: 208,
    publisher: "HarperOne",
    year: 1988,
    badge: "Bestseller",
    featured: true,
  },
  {
    id: 12,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    category: "Finance",
    price: 649,
    rating: 4.5,
    reviews: 5540,
    cover: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&q=80",
    description:
      "What the rich teach their kids about money that the poor and middle class do not.",
    pages: 336,
    publisher: "Plata Publishing",
    year: 1997,
    badge: null,
    featured: true,
  },
  {
    id: 13,
    title: "The 3 Mistakes of My Life",
    author: "Chetan Bhagat",
    category: "Fiction",
    rating: 4.1,
    reviews: 17800,
    price: 199,
    cover: "https://images-na.ssl-images-amazon.com/images/I/81af+MCATTL.jpg",
    description: "A story of friendship, ambition, and mistakes set in Ahmedabad.",
    pages: 258,
    publisher: "Rupa Publications",
    year: 2008,
    badge: "Popular",
    featured: false,
  },
  {
    id:14,
     title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    category: "Biography",
    rating: 4.7,
    reviews: 25600,
    price: 199,
    cover: "https://images-na.ssl-images-amazon.com/images/I/71KKZlVjbwL.jpg",
    description: "An inspiring autobiography of Dr. A.P.J. Abdul Kalam, from a small-town boy to India's Missile Man.",
    pages: 180,
    publisher: "Universities Press",
    year: 1999,
    badge: "Must Read",
    featured: true,
  },
  {
    id:15,
    title: "The Guide",
    author: "R.K. Narayan",
    category: "Fiction",
    rating: 4.2,
    reviews: 6200,
    price: 199,
    cover: "https://images-na.ssl-images-amazon.com/images/I/81vpsIs58WL.jpg",
    description: "A classic Indian novel about transformation, love, and spirituality.",
    pages: 292,
    publisher: "Indian Thought Publications",
    year: 1958,
    badge: "Bestseller",
    featured: true,
  },
  {
  id: 16,
  title: "India's Struggle for Independence",
  author: "Bipan Chandra",
  category: "History",
  rating: 4.6,
  reviews: 18500,
  price: 399,
  cover: "https://images-na.ssl-images-amazon.com/images/I/81t2CVWEsUL.jpg",
  description: "A comprehensive account of India's freedom struggle, covering key movements, leaders, and events from 1857 to 1947.",
  pages: 600,
  publisher: "Penguin India",
  year: 1988,
  badge: "Bestseller",
   featured: false, 
},
{
  id: 17,
  title: "The Discovery of India",
  author: "Jawaharlal Nehru",
  category: "History",
  rating: 4.5,
  reviews: 14200,
  price: 349,
  cover: "https://images-na.ssl-images-amazon.com/images/I/91M9xPIf10L.jpg",
  description: "Written during imprisonment, this book explores India's rich history, culture, and heritage from ancient to modern times.",
  pages: 576,
  publisher: "Penguin India",
  year: 1946,
  badge: "Classic",
   featured: false, 
},
{
   id: 18,
  title: "India After Gandhi",
  author: "Ramachandra Guha",
  category: "History",
  rating: 4.7,
  reviews: 21500,
  price: 499,
  cover: "https://images-na.ssl-images-amazon.com/images/I/81g2oEdeGTL.jpg",
  description: "A detailed and engaging account of India's journey after independence, covering political, social, and economic developments.",
  pages: 900,
  publisher: "Picador India",
  year: 2007,
  badge: "Top Bestseller",
  featured: true, 
},
{
  id: 19,
  title: "An Era of Darkness",
  author: "Shashi Tharoor",
  category: "History",
  rating: 4.6,
  reviews: 19800,
  price: 399,
  cover: "https://m.media-amazon.com/images/I/81flaySX1xL._SL1500_.jpg",
  description: "A powerful critique of British colonial rule in India, highlighting its economic and cultural impact.",
  pages: 336,
  publisher: "Aleph Book Company",
  year: 2016,
  badge: "Highly Rated",
  featured: false, 
}

];

export const categories = ["All", "Fiction", "Non-Fiction", "Sci-Fi", "Self-Help", "Finance", "History"];
